title: Lemming Law
url: https://lemminglaw.com
homepage: https://lemminglaw.com
description: authoritative retorts to common, pointless legalisms
logo: https://lemminglaw.com/lemmings.svg
exclude:
  - README.md
  - CONTRIBUTING.md
  - Makefile
